name: MineOnlineBroadcast
version: 1.0.7
description: Lists a server on mineonline.codie.gg/servers
author: codieradical
authors: [Codie]
website: https://mineonline.codie.gg/

main: MineOnlineBroadcast
database: false
depend: []