name: MineOnlineBroadcast
version: 1.0.1
description: Lists a server on mineonline.codie.gg/servers
author: codieradical
authors: [Codie]
website: http://mineonline.codie.gg/

main: MineOnlineBroadcast
database: false
depend: []